version: '3.8'

services:
  web:
    container_name: web
    build: frontend
    image: frontend:latest
    networks:
      - object-detection
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - yolo5

  yolo5:
    container_name: yolo5
    build: yolo5:0.1
    networks:
      - object-detection
    image: vaibhavrawat/yolo:0.2.0
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    ports:
      - "8081:8081"

  mongodb:
    container_name: mongodb
    image: mongo:latest

    networks:
      - object-detection
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - ./mongo/data:/data/db

  polybot:
    container_name: polybot
    image: polybot:0.1
    networks:
      - object-detection
    depends_on:
      - yolo5


volumes:
  mongodb:
    driver: local

networks:
  object-detection:
    name: object-detection
    driver: bridge
